#!/bin/bash

echo "🚀 Iniciando el sistema de ventas..."
echo "📁 Estructura del proyecto creada"
echo "🐳 Docker Compose configurado"
echo ""
echo "Para iniciar el sistema:"
echo "1. docker-compose up -d --build"
echo ""
echo "URLs disponibles:"
echo "🌐 Aplicación: http://localhost:8000"
echo "📊 phpMyAdmin: http://localhost:8080"
echo ""
echo "👤 Usuario de prueba:"
echo "Email: admin@test.com"
echo "Password: admin123"
echo ""
echo "🔧 Estructura de archivos PHP:"
echo "  📄 src/index.php - Redireccionamiento inicial"
echo "  🔐 src/auth/login.php - Página de inicio de sesión"
echo "  🔐 src/auth/logout.php - Cerrar sesión"
echo "  🏠 src/dashboard.php - Panel principal"
echo "  ⚙️ src/config/database.php - Conexión a BD"
echo "  📱 src/auth/session.php - Manejo de sesiones"
echo ""
echo "✅ Sistema configurado exitosamente!"
